### ISSUE TITLE
共有ボタンの実装

### ISSUE THREAD

**Issue by Reon0429-cat** [Reon0429-cat/PetSNS#35]

**Comment by tatsuya-ss** [comment]
@Reon0429-cat @sagaraEito 
共有ボタンってこのxibのフォロー中の横に付けるという認識で合ってますか？

<img width="963" alt="スクリーンショット 2021-09-06 17 38 20" src="https://user-images.githubusercontent.com/72326299/132187176-2118ee45-9914-42f3-a3aa-6b914570d7b3.png">

![スクリーンショット 2021-09-06 17 36 39](https://user-images.githubusercontent.com/72326299/132186745-7de038ac-0f41-4586-a1b4-00eb78dafc4a.png)

**Comment by Reon0429-cat** [comment]
あ、これ違うかもしれないですね。設定画面の方かもです
![ScreenShot 2021-09-06 17 46 37](https://user-images.githubusercontent.com/66917548/132188241-3aee0914-59f3-4836-bf12-6ab6c1632d18.png)

**Comment by tatsuya-ss** [comment]
確認してよかったです笑
ありがとうございます！

**Comment by tatsuya-ss** [comment]
なるほどです。
今回は設定画面の方でしたね。ありがとうございます！
